(load (compile-file "math-util.lisp"))
(defun multiple-3-or-5 (x)
  (or (zerop (rem x 3)) (zerop (rem x 5))))
(defun main()
(format t "~a~%" (reduce #'+ (remove-if-not #'multiple-3-or-5 (range 1 1000))))
)
